# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yin/SatelliteSim/FrontEnd/mainWindow/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(190, 70, 771, 531))
        self.widget.setObjectName("widget")
        self.SelectSatellites = QtWidgets.QPushButton(self.centralwidget)
        self.SelectSatellites.setGeometry(QtCore.QRect(0, 100, 181, 31))
        self.SelectSatellites.setObjectName("SelectSatellites")
        self.newwindow_bt = QtWidgets.QPushButton(self.centralwidget)
        self.newwindow_bt.setGeometry(QtCore.QRect(10, 150, 121, 31))
        self.newwindow_bt.setObjectName("newwindow_bt")
        self.input_btn = QtWidgets.QPushButton(self.centralwidget)
        self.input_btn.setGeometry(QtCore.QRect(30, 220, 89, 25))
        self.input_btn.setObjectName("input_btn")
        self.logBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.logBox.setGeometry(QtCore.QRect(1035, 380, 240, 201))
        self.logBox.setObjectName("logBox")
        self.statusBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.statusBox.setGeometry(QtCore.QRect(1035, 30, 240, 341))
        self.statusBox.setObjectName("statusBox")
        self.continue_btn = QtWidgets.QPushButton(self.centralwidget)
        self.continue_btn.setGeometry(QtCore.QRect(40, 280, 89, 25))
        self.continue_btn.setObjectName("continue_btn")
        self.encoderComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.encoderComboBox.setGeometry(QtCore.QRect(130, 10, 86, 25))
        self.encoderComboBox.setObjectName("encoderComboBox")
        self.encoderComboBox.addItem("")
        self.encoderComboBox.addItem("")
        self.encoderComboBox.addItem("")
        self.encoderLabel = QtWidgets.QLabel(self.centralwidget)
        self.encoderLabel.setGeometry(QtCore.QRect(60, 10, 67, 17))
        self.encoderLabel.setObjectName("encoderLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1302, 28))
        self.menubar.setObjectName("menubar")
        self.menuEarth = QtWidgets.QMenu(self.menubar)
        self.menuEarth.setObjectName("menuEarth")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuEarth.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SelectSatellites.setText(_translate("MainWindow", "Send Selected Satellites"))
        self.newwindow_bt.setText(_translate("MainWindow", "Watcher"))
        self.input_btn.setText(_translate("MainWindow", "Set Input"))
        self.continue_btn.setText(_translate("MainWindow", "Continue"))
        self.encoderComboBox.setItemText(0, _translate("MainWindow", "CRC"))
        self.encoderComboBox.setItemText(1, _translate("MainWindow", "Parity Check-Odd"))
        self.encoderComboBox.setItemText(2, _translate("MainWindow", "Parity Check-Even"))
        self.encoderLabel.setText(_translate("MainWindow", "Encoder"))
        self.menuEarth.setTitle(_translate("MainWindow", "Earth"))
