# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yin/SatelliteSim/FrontEnd/watcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Watcher(object):
    def setupUi(self, Watcher):
        Watcher.setObjectName("Watcher")
        Watcher.resize(904, 511)
        self.subplt1 = QtWidgets.QWidget(Watcher)
        self.subplt1.setGeometry(QtCore.QRect(30, 50, 400, 250))
        self.subplt1.setObjectName("subplt1")
        self.text1 = QtWidgets.QTextEdit(self.subplt1)
        self.text1.setGeometry(QtCore.QRect(0, 0, 401, 251))
        self.text1.setObjectName("text1")
        self.subtitle1 = QtWidgets.QLabel(Watcher)
        self.subtitle1.setGeometry(QtCore.QRect(190, 310, 67, 17))
        self.subtitle1.setObjectName("subtitle1")
        self.subplt2 = QtWidgets.QWidget(Watcher)
        self.subplt2.setGeometry(QtCore.QRect(450, 50, 400, 250))
        self.subplt2.setObjectName("subplt2")
        self.subtitle2 = QtWidgets.QLabel(Watcher)
        self.subtitle2.setGeometry(QtCore.QRect(590, 310, 67, 17))
        self.subtitle2.setObjectName("subtitle2")
        self.subSlider1 = QtWidgets.QSlider(Watcher)
        self.subSlider1.setGeometry(QtCore.QRect(140, 350, 160, 16))
        self.subSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.subSlider1.setObjectName("subSlider1")
        self.SyncCheckBox = QtWidgets.QCheckBox(Watcher)
        self.SyncCheckBox.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.SyncCheckBox.setObjectName("SyncCheckBox")
        self.subSlider2 = QtWidgets.QSlider(Watcher)
        self.subSlider2.setGeometry(QtCore.QRect(550, 350, 160, 16))
        self.subSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.subSlider2.setObjectName("subSlider2")
        self.CloseButton = QtWidgets.QPushButton(Watcher)
        self.CloseButton.setGeometry(QtCore.QRect(380, 420, 89, 25))
        self.CloseButton.setObjectName("CloseButton")

        self.retranslateUi(Watcher)
        self.CloseButton.pressed.connect(Watcher.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Watcher)

    def retranslateUi(self, Watcher):
        _translate = QtCore.QCoreApplication.translate
        Watcher.setWindowTitle(_translate("Watcher", "Watcher"))
        self.subtitle1.setText(_translate("Watcher", "TextLabel"))
        self.subtitle2.setText(_translate("Watcher", "TextLabel"))
        self.SyncCheckBox.setText(_translate("Watcher", "Sync"))
        self.CloseButton.setText(_translate("Watcher", "Close"))
