# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yin/SatelliteSim/FrontEnd/watcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Watcher(object):
    def setupUi(self, Watcher):
        Watcher.setObjectName("Watcher")
        Watcher.resize(400, 300)
        self.subplt1 = QtWidgets.QWidget(Watcher)
        self.subplt1.setGeometry(QtCore.QRect(40, 20, 151, 111))
        self.subplt1.setObjectName("subplt1")
        self.subtitle1 = QtWidgets.QLabel(Watcher)
        self.subtitle1.setGeometry(QtCore.QRect(70, 140, 67, 17))
        self.subtitle1.setObjectName("subtitle1")

        self.retranslateUi(Watcher)
        QtCore.QMetaObject.connectSlotsByName(Watcher)

    def retranslateUi(self, Watcher):
        _translate = QtCore.QCoreApplication.translate
        Watcher.setWindowTitle(_translate("Watcher", "Watcher"))
        self.subtitle1.setText(_translate("Watcher", "示波器1"))
