# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yin/SatelliteSim/FrontEnd/query/query.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 40, 341, 181))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 81, 21))
        self.label.setObjectName("label")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(180, 250, 89, 25))
        self.cancelButton.setObjectName("cancelButton")
        self.submitButton = QtWidgets.QPushButton(Dialog)
        self.submitButton.setGeometry(QtCore.QRect(280, 250, 89, 25))
        self.submitButton.setObjectName("submitButton")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(110, 10, 86, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.selectButton = QtWidgets.QPushButton(Dialog)
        self.selectButton.setGeometry(QtCore.QRect(328, 130, 31, 20))
        self.selectButton.setObjectName("selectButton")
        self.pathlabel = QtWidgets.QLabel(Dialog)
        self.pathlabel.setGeometry(QtCore.QRect(66, 130, 241, 21))
        self.pathlabel.setObjectName("pathlabel")
        self.Path = QtWidgets.QLabel(Dialog)
        self.Path.setGeometry(QtCore.QRect(10, 130, 41, 21))
        self.Path.setObjectName("Path")

        self.retranslateUi(Dialog)
        self.cancelButton.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Input Type"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.submitButton.setText(_translate("Dialog", "Submit"))
        self.comboBox.setItemText(0, _translate("Dialog", "TEXT"))
        self.comboBox.setItemText(1, _translate("Dialog", "VOICE"))
        self.selectButton.setText(_translate("Dialog", "..."))
        self.pathlabel.setText(_translate("Dialog", "TextLabel"))
        self.Path.setText(_translate("Dialog", "Path:"))
