# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/yin/SatelliteSim/FrontEnd/watcher/watcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Watcher(object):
    def setupUi(self, Watcher):
        Watcher.setObjectName("Watcher")
        Watcher.resize(904, 511)
        self.subtitle1 = QtWidgets.QLabel(Watcher)
        self.subtitle1.setGeometry(QtCore.QRect(190, 310, 67, 17))
        self.subtitle1.setObjectName("subtitle1")
        self.subtitle2 = QtWidgets.QLabel(Watcher)
        self.subtitle2.setGeometry(QtCore.QRect(590, 310, 67, 17))
        self.subtitle2.setObjectName("subtitle2")
        self.subSlider1 = QtWidgets.QSlider(Watcher)
        self.subSlider1.setGeometry(QtCore.QRect(140, 350, 160, 16))
        self.subSlider1.setOrientation(QtCore.Qt.Horizontal)
        self.subSlider1.setObjectName("subSlider1")
        self.SyncCheckBox = QtWidgets.QCheckBox(Watcher)
        self.SyncCheckBox.setGeometry(QtCore.QRect(20, 10, 101, 31))
        self.SyncCheckBox.setObjectName("SyncCheckBox")
        self.subSlider2 = QtWidgets.QSlider(Watcher)
        self.subSlider2.setGeometry(QtCore.QRect(550, 350, 160, 16))
        self.subSlider2.setOrientation(QtCore.Qt.Horizontal)
        self.subSlider2.setObjectName("subSlider2")
        self.CloseButton = QtWidgets.QPushButton(Watcher)
        self.CloseButton.setGeometry(QtCore.QRect(380, 420, 89, 25))
        self.CloseButton.setObjectName("CloseButton")
        self.watcherSelect = QtWidgets.QComboBox(Watcher)
        self.watcherSelect.setGeometry(QtCore.QRect(110, 10, 86, 25))
        self.watcherSelect.setObjectName("watcherSelect")
        self.watcherSelect.addItem("")
        self.stackedWidget = QtWidgets.QStackedWidget(Watcher)
        self.stackedWidget.setGeometry(QtCore.QRect(40, 50, 391, 241))
        self.stackedWidget.setObjectName("stackedWidget")
        self.plt_page = QtWidgets.QWidget()
        self.plt_page.setObjectName("plt_page")
        self.subplt1 = QtWidgets.QWidget(self.plt_page)
        self.subplt1.setGeometry(QtCore.QRect(-10, -10, 400, 250))
        self.subplt1.setObjectName("subplt1")
        self.stackedWidget.addWidget(self.plt_page)
        self.text_page = QtWidgets.QWidget()
        self.text_page.setObjectName("text_page")
        self.text1 = QtWidgets.QTextEdit(self.text_page)
        self.text1.setGeometry(QtCore.QRect(0, 0, 391, 241))
        self.text1.setObjectName("text1")
        self.stackedWidget.addWidget(self.text_page)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(Watcher)
        self.stackedWidget_2.setGeometry(QtCore.QRect(480, 50, 351, 241))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.subplt2 = QtWidgets.QWidget(self.page)
        self.subplt2.setGeometry(QtCore.QRect(0, 0, 341, 231))
        self.subplt2.setObjectName("subplt2")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.text2 = QtWidgets.QTextEdit(self.page_2)
        self.text2.setGeometry(QtCore.QRect(10, 10, 341, 231))
        self.text2.setObjectName("text2")
        self.stackedWidget_2.addWidget(self.page_2)

        self.retranslateUi(Watcher)
        self.stackedWidget.setCurrentIndex(1)
        self.CloseButton.pressed.connect(Watcher.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Watcher)

    def retranslateUi(self, Watcher):
        _translate = QtCore.QCoreApplication.translate
        Watcher.setWindowTitle(_translate("Watcher", "Watcher"))
        self.subtitle1.setText(_translate("Watcher", "TextLabel"))
        self.subtitle2.setText(_translate("Watcher", "TextLabel"))
        self.SyncCheckBox.setText(_translate("Watcher", "Sync"))
        self.CloseButton.setText(_translate("Watcher", "Close"))
        self.watcherSelect.setItemText(0, _translate("Watcher", "AD"))
